# Generated by Django 3.0.2 on 2020-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QryCond', models.CharField(max_length=200)),
                ('StartPage', models.IntegerField(default=0)),
                ('StopPage', models.IntegerField(default=0)),
                ('DataType', models.CharField(max_length=10)),
                ('TurnOffChrome', models.CharField(max_length=200)),
                ('HeadlessMode', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
