# Generated by Django 3.0.2 on 2020-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
